# Generated by Django 5.2.16 on 2026-08-16 17:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentcollaborator',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentcollaborator',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_document_collaborators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentcollaborator',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='change_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddConstraint(
            model_name='documentcollaborator',
            constraint=models.UniqueConstraint(fields=('document', 'user'), name='unique_document_collaborator'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='unique_document_version'),
        ),
    ]
